### ISSUE TITLE
H100 unprotected memory

### ISSUE THREAD

**Issue by Tan-YiFan** [NVIDIA/nvtrust#20]
`nvidia-smi conf-compute` provides an interface to configure unprotected video memory:

```
# Recorded in file "nvidia-smi.1"
.TP 15
.B 9) Set confidential compute GPU unprotected memory size
.TP 15
.I nvidia-smi conf-compute -sm <value>
.TP 15
.I nvidia-smi conf-compute --set-unprotected-mem-size <value>
.TP 15
Set confidential compute GPU unprotected memory size in KiB. Requires root.
```

However, according to the code of [kernel module](https://github.com/NVIDIA/open-gpu-kernel-modules/blob/545.29.02/src/nvidia/src/kernel/gpu/conf_compute/conf_compute_api.c#L207-L217), this api call would not have any effect.

What is the usage of unprotected memory?

**Comment by rnertney** [comment]
Correct. This NVML currently has no effect and was created for a potential future use. It has no effect on the security posture of CC overall.

**Comment by Tan-YiFan** [comment]
@rnertney Thanks!

By the way, could protected memory to be the source or destination of Nv-Link (GPU peer-to-peer) transfer? Or unprotected memory is used?
