### ISSUE TITLE
Is it possible that an H100 in CC mode can pass some plaintext to another H100 not in CC mode through NVLINK?

### ISSUE THREAD

**Issue by AmbitionXiang** [NVIDIA/nvtrust#22]
Is it possible that an H100 in CC mode can pass some plaintext to another H100 not in CC mode through NVLINK? It seems that the H100 in CC mode forces the data to be encrypted as the data leaves GPU protected memory?

**Comment by rnertney** [comment]
We disable `PeerAccess` when we are in CC mode. You will not be able to perform any P2P accesses in the current release.
