### ISSUE TITLE
About GPU CC NVLink

### ISSUE THREAD

**Issue by Tan-YiFan** [NVIDIA/nvtrust#24]
It seems that H100 CC Early Access only supports a single H100 GPU, without NVLink.

However, the H100 whitepaper implies that H100 CC would support multi-GPU cases with NVLink. I am curious about some details in the multi-GPU cases:

1. According Figure 12 of [the white paper](https://images.nvidia.cn/aem-dam/en-zz/Solutions/data-center/HCC-Whitepaper-v1.0.pdf), GPU unprotected memory involves P2P bounce buffer. Why don't P2P transfer directly store the output of encryption engine (hopper CE) to compute protected region (CPR)? 

2. What is the default value of GPU unprotected memory? Would modifying this size require resetting the GPU (or is modifiable at runtime)?

**Comment by Tan-YiFan** [comment]
Add a question:

3. Who has the responsibility of maintaining the P2P bounce buffer? The kernel-mode driver, the user-mode CUDA driver, or both?

**Comment by Tan-YiFan** [comment]
4. H100 GPUs have CC mode. Does NvSwitch also have the similar CC mode? @rnertney @steven-bellock

**Comment by rnertney** [comment]
Our Multi GPU solution details will come in a future release. Unfortunately we cannot comment beforehand.
