### ISSUE TITLE
Is MMIO of H100 CC Encrypted?

### ISSUE THREAD

**Issue by Tan-YiFan** [NVIDIA/nvtrust#26]
Hi @rnertney ,

I am analyzing the attack vectors of H100 confidential computing.

It is clear that the data payload is encrypted using AES-GCM256. However, is MMIO also encrypted?

If the MMIO is **not** encrypted, the attacker could modify it to destroy the integrity. For example:

* CVM launches a host-to-device memcpy MMIO.
* The attacker cancels this MMIO, while making CVM feel that the MMIO is finished.
* The computation result would be unexpected.

**Comment by Tan-YiFan** [comment]
The [whitepaper](https://images.nvidia.com/aem-dam/en-zz/Solutions/data-center/HCC-Whitepaper-v1.0.pdf) said,

> The receiving endpoint performing the decryption doesn’t use the IV sent by the encrypting transmitter, instead it uses its own.

What's the problem if the receiving endpoint use the IV sent by the transmitter?

**Comment by steven-bellock** [comment]
> What's the problem if the receiving endpoint use the IV sent by the transmitter?

Replay attack. If the receiving endpoint blindly uses the IV sent by the transmitting endpoint then an interposer can replay old messages in arbitrary order.

**Comment by Tan-YiFan** [comment]
@steven-bellock I found some MMIO macros in the driver source code ([link](https://github.com/NVIDIA/open-gpu-kernel-modules/blob/535.86.10/kernel-open/nvidia-uvm/clc8b5.h#L279-L284)). If IV could be transferred by secure MMIO (encrypted MMIO) using this MMIO port, would replay attack still work?

**Comment by steven-bellock** [comment]
Those registers were included for debugging but aren't used in production. When the GPU decrypts it uses its internal IV counter and when the CPU decrypts it uses https://github.com/NVIDIA/open-gpu-kernel-modules/blob/4c29105335610933e744f4ab2524ea63fc39edaf/src/nvidia/src/kernel/gpu/conf_compute/ccsl.c#L476

and

https://github.com/NVIDIA/open-gpu-kernel-modules/blob/4c29105335610933e744f4ab2524ea63fc39edaf/src/nvidia/src/kernel/gpu/conf_compute/ccsl.c#L665

The GPU has a "hitch" where, when it encrypts data, it must write the IV to unprotected system memory, even in production. This IV is ignored on the CPU-side.

**Comment by Tan-YiFan** [comment]
@steven-bellock Thanks for explaining the procedure of current design.

Can I **manually configure the IV on the GPU** by writing the MMIO `NVC8B5_SET_DECRYPT_IV0` in the guest driver? The suffix of the MMIO is `VALUE` so it seems that value instead of address (unprotected system memory) is passed.

There are two possible approaches to it:

1. Use the above-mentioned MMIO. Would the IV passed through MMIO be leaked or modified by attacker?
2. Copy the encrypted IV to GPU video memory, and issue a MMIO to set the IV (on the GPU) as the new IV. However, I did not found any MMIO interface to implement it.

**Comment by steven-bellock** [comment]
> Can I manually configure the IV on the GPU by writing the MMIO NVC8B5_SET_DECRYPT_IV0 in the guest driver?

No. Like I said that is ignored by the GPU when in production, and it uses its internal counter.

**Comment by Tan-YiFan** [comment]
@steven-bellock OK. So there is no way for guest driver to configure the counter on the GPU?

**Comment by steven-bellock** [comment]
When a channel is allocated or a channel's IV is rotated its initial IV is transmitted from CPU to GPU. After the initial programming, the GPU's IV counter is incremented independently of the CPU.

**Comment by Tan-YiFan** [comment]
@steven-bellock 
> When a channel is allocated or a channel's IV is rotated its initial IV is transmitted from CPU to GPU.

Is the initial IV generated by CPU? The code `updatedKmb [OUT]` of rotate IV param ([link](https://github.com/NVIDIA/open-gpu-kernel-modules/blob/535.86.10/src/common/sdk/nvidia/inc/ctrl/ctrlc56f.h#L192)) implies that the initial IV is generated by GPU.

**Comment by steven-bellock** [comment]
That control call does double duty, as a control call from CPU-RM clients (CUDA / UVM) to rotate the IV, as well as a control call between CPU-RM and GSP-RM to rotate the IV on the GPU side. When it is the former it's `OUT` and when it is the latter it's `IN`. I can update the code to reflect that. The [Keystore](https://github.com/NVIDIA/open-gpu-kernel-modules/blob/main/src/nvidia/src/kernel/gpu/conf_compute/arch/hopper/conf_compute_keystore_gh100.c) is in charge of generating initial IVs and preventing IV reuse.

**Comment by Tan-YiFan** [comment]
@steven-bellock Thanks. You mentioned that CUDA can rotate the IV. Does it mean CUDA (user-mode) maintain its own keystore (key and IV) and use a channel different from kernel-mode UVM?

**Comment by steven-bellock** [comment]
Correct, kernel drivers and user-mode drivers wield separate keys, and user-mode drivers have a copy of the key. Note that while the CPU-side is in charge of rotating the IV, the GPU hardware will not allow overflow of the IV counter. Ie, if the IV counter is at its maximum value and the CPU attempts to get the GPU to encrypt some data, the GPU will error out, and the session is effectively ended.

**Comment by Tan-YiFan** [comment]
@steven-bellock Thank you for explaining the keystore system of cuda! I have no access to this part of cuda code so this is new to me. By the way, does it imply that cuda can manage unprotected memory of CPU, just like the [dma buffer pool](https://github.com/NVIDIA/open-gpu-kernel-modules/blob/main/kernel-open/nvidia-uvm/uvm_conf_computing.c#L95) in kernel driver?

**Comment by steven-bellock** [comment]
CUDA can encrypt to unprotected system memory and decrypt from it, but it relies on the kernel to allocate and manage memory.

**Comment by Tan-YiFan** [comment]
@steven-bellock Is the key rotation **done** by GPU? According to [src/nvidia/src/kernel/gpu/conf_compute/ccsl.c](https://github.com/NVIDIA/open-gpu-kernel-modules/blob/545.29.06/src/nvidia/src/kernel/gpu/conf_compute/ccsl.c#L349-L392), the rotation command is sent by CPU, done by GPU and then the CPU receives the new IV.

**Comment by Tan-YiFan** [comment]
@steven-bellock I saw two files related to keystore in the driver code: `conf_compute_keystore_gh100.c` and `conf_compute_keystore.c`. The former one maintains [one crypto bundle for encryption and decryption](https://github.com/NVIDIA/open-gpu-kernel-modules/blob/545.29.06/src/nvidia/src/kernel/gpu/conf_compute/arch/hopper/conf_compute_keystore_gh100.c#L57) while the latter one maintains [one bundle for encryption and one for decryption](https://github.com/NVIDIA/open-gpu-kernel-modules/blob/545.29.06/src/nvidia/src/kernel/gpu/conf_compute/conf_compute_keystore.c#L33-L48). In H100, which one would be used (H2D and D2H use the same key or not)?

**Comment by steven-bellock** [comment]
> @steven-bellock Is the key rotation **done** by GPU? According to [src/nvidia/src/kernel/gpu/conf_compute/ccsl.c](https://github.com/NVIDIA/open-gpu-kernel-modules/blob/545.29.06/src/nvidia/src/kernel/gpu/conf_compute/ccsl.c#L349-L392), the rotation command is sent by CPU, done by GPU and then the CPU receives the new IV.

No. CPU generates the new IV.

**Comment by Tan-YiFan** [comment]
@steven-bellock

> CPU generates the new IV.

Is the IV rotation logic implemented in the function `ccslRotateIv_IMPL` [link](https://github.com/NVIDIA/open-gpu-kernel-modules/blob/545.29.06/src/nvidia/src/kernel/gpu/conf_compute/ccsl.c#L319)? This function would call `kchannelCtrlRotateSecureChannelIv_KERNEL` [link](https://github.com/NVIDIA/open-gpu-kernel-modules/blob/545.29.06/src/nvidia/src/kernel/gpu/fifo/kernel_channel.c#L4435) which will then call function in keystore_h100.

It seems that key rotation is not supported in EA, I could not test it and get back trace.

**Comment by steven-bellock** [comment]
> It seems that key rotation is not supported in EA

Key rotation is not, but IV rotation is. In EA if the tenant wants new keys then they'd need to save their work, tear down the confidential compute session, and then reestablish it.

**Comment by Tan-YiFan** [comment]
>  If the tenant wants new keys

The driver [code](https://github.com/NVIDIA/open-gpu-kernel-modules/blob/545.29.06/kernel-open/common/inc/nv_uvm_types.h#L341) (macro `UVM_COPY_ENGINE_COUNT_MAX`) implies that H100 has more than one copy engine (with the same number of secure channel). Each channel would have its own key different from other channels'. Could key rotation be implemented by channel switching?

**Comment by Tan-YiFan** [comment]
@steven-bellock The function `csl_init` initializes the key of each channel. Are the keys of those channels the same?

**Comment by Tan-YiFan** [comment]
@steven-bellock I guess CUDA and kernel UVM (of the same tenant) use different keys. It that true?

**Comment by Tan-YiFan** [comment]
@steven-bellock About data transfer between CPU and GPU, data copy using `cudaMemcpy` would use CUDA key; and data copy using `cudaMemcpyAsync` (with `cudaMallocHost`) and UVM would use kernel-driver UVM key. Is that true?

If so, can those two procedures work concurrently, to achieve double bandwidth (4GB/s => 8GB/s)?

**Comment by Tan-YiFan** [comment]
> Yes, check out https://github.com/NVIDIA/open-gpu-kernel-modules/blob/main/src/nvidia/arch/nvalloc/common/inc/conf_compute/cc_keystore.h for all the keys. The `P2P` ones are currently unused.

@steven-bellock `D2H` and `H2D` use different key ids for both user and kernel. Does it imply that in kernel mode, CPU-side encryption and decryption would use different keys?

**Comment by steven-bellock** [comment]
> Does it imply that in kernel mode, CPU-side encryption and decryption would use different keys?

Yes. User mode as well.

**Comment by Tan-YiFan** [comment]
@steven-bellock In kernel driver, one IV serves 4096 bytes because it is the size of one page in UVM. Could IV of user-space cuda serves more than 4KB (or does it have an upper limit) data?

**Comment by steven-bellock** [comment]
>Could IV of user-space cuda serves more than 4KB (or does it have an upper limit) data?

Yes, support for encryption sizes ranging from bytes to gigabytes are supported by both the GPU and the CPU. The size of the bounce buffers in unprotected system memory obviously limits the size of large encryptions.

**Comment by Tan-YiFan** [comment]
@steven-bellock Inside a VM, does all cuda applications (using MPS or cuda stream to share the GPU) use the same user-level key (and IV)?

**Comment by steven-bellock** [comment]
Processes that share the same copy engine use the same key. The IV space is divided though, to prevent IV reuse.

**Comment by Tan-YiFan** [comment]
@steven-bellock

In HtoD data transfer, the encryption is done by CPU-side driver. According to [encryption function in UVM](https://github.com/NVIDIA/open-gpu-kernel-modules/blob/535.104.05/kernel-open/nvidia-uvm/uvm_va_block.c#L2927-L2932), it seems that the ciphertext buffer is allocated in CVM shared memory (dma_buffer).

May I ask:

* In **kernel-mode UVM**, does the ciphertext buffer of CPU-side encryption allocated in CVM shared memory?
* In **user-mode CUDA**, does the ciphertext buffer of CPU-side encryption allocated in CVM shared memory?

**Comment by steven-bellock** [comment]
Yes and yes.

**Comment by steven-bellock** [comment]
>Does cuda use AVX512 for encryption?

CUDA calls into the installed OpenSSL (actually libnvidia-pkcs11 that calls into OpenSSL) library to perform encryption/decryption so that is up to the installed OpensSSL. When the driver is built it uses the header files from OpenSSL 3.0.7, so if OpenSSL 3.1/3.2 is API and ABI compatible with 3.0 then there shouldn't be a problem (one hopes).

>Can we use multi-threading encryption?

Define "we". A CUDA application compiled with `nvcc`, the CUDA driver, or something else?

**Comment by Tan-YiFan** [comment]
@steven-bellock Can "the CUDA driver and Nvidia open-sourced driver" use multi-threading encryption?

**Comment by steven-bellock** [comment]
They can. Whether or not they will depends on performance goals and pain points. These have to be balanced within security and complexity constraints.

**Comment by Tan-YiFan** [comment]
@steven-bellock In cuda 12.2.2 (the version of Nvidia Confidential Computing Early Release), has cuda implemented the multi-threading encryption approach?

**Comment by steven-bellock** [comment]
For separate channels, yes.
