### ISSUE TITLE
failed to open /dev/vfio/47: No such file or directory

### ISSUE THREAD

**Issue by seungsoo-lee** [NVIDIA/nvtrust#32]
I failed to launch CVM as described on the deployment document.

on the host,

when executing ```./launch_vm.sh``` on ```/shared/nvtrust/host_tools/sample_kvm_scripts```

it says
```
qemu-system-x86_64: -device vfio-pci,host=44:00.0,bus=pci.1: vfio 0000:44:00.0: failed to open /dev/vfio/47: No such file or directory
```

but, on the host,
```
cclab@ubuntu-h100:~$ lspci | grep NVIDIA
44:00.0 3D controller: NVIDIA Corporation Device 2331 (rev a1)
```
and I already did ```sudo sh -c "echo 10de 2331 > /sys/bus/pci/drivers/vfio-pci/new_id"```

what's the problem..?

**Comment by Tan-YiFan** [comment]
Method 1: Uninstall the Nvidia driver on the host, and then reboot the system.
Method 2:

* On the host, `sudo lsof /dev/nvidia0` and kill the related processes.
* On the host, `sudo sh -c "echo 0000:44:00.0 > /sys/bus/pci/devices/0000:44:00.0/driver/unbind"`
* Then, on the host, `sudo sh -c "echo 10de 2331 > /sys/bus/pci/drivers/vfio-pci/new_id"`

You would check whether it succeeds by `ls /dev/vfio`

**Comment by seungsoo-lee** [comment]
@Tan-YiFan 

as your advice, I run the commands but there is somthing wrong.

```
cclab@host-h100:~$ sudo lsof /dev/nvidia0
lsof: status error on /dev/nvidia0: No such file or directory
lsof 4.93.2
 latest revision: https://github.com/lsof-org/lsof
 latest FAQ: https://github.com/lsof-org/lsof/blob/master/00FAQ
 latest (non-formatted) man page: https://github.com/lsof-org/lsof/blob/master/Lsof.8
 usage: [-?abhKlnNoOPRtUvVX] [+|-c c] [+|-d s] [+D D] [+|-E] [+|-e s] [+|-f[gG]]
 [-F [f]] [-g [s]] [-i [i]] [+|-L [l]] [+m [m]] [+|-M] [-o [o]] [-p s]
 [+|-r [t]] [-s [p:s]] [-S [t]] [-T [t]] [-u s] [+|-w] [-x [fl]] [--] [names]
Use the ``-h'' option to get more help information.

cclab@host-h100:~$ sudo sh -c "echo 0000:44:00.0 > /sys/bus/pci/devices/0000:44:00.0/driver/unbind"
sh: 1: cannot create /sys/bus/pci/devices/0000:44:00.0/driver/unbind: Directory nonexistent
```

for now there is no NVIDIA driver on the host as I did re-install Ubuntu 22.04. however, unlike the previous, when I start the guest VM, it says.. 
```
qemu-system-x86_64: -device vfio-pci,host=44:00.0,bus=pci.1: vfio 0000:44:00.0: failed to open /dev/vfio/47: No such file or directory
```

confused. I could not figure it out what's the problem now.

**Comment by Tan-YiFan** [comment]
After you execute the command about vfio-pci/new_id, does any error occur in dmesg?

**Comment by seungsoo-lee** [comment]
@Tan-YiFan 

it solved thanks..

**Comment by jianlinjiang** [comment]
@seungsoo-lee  hi I also met the same issue， how you solved it?
