### ISSUE TITLE
"No devices found" with 535.104.05 and AMD SEV-SNP VM

### ISSUE THREAD

**Issue by derpsteb** [NVIDIA/nvtrust#34]
Hello,
I am working with an Nvidia H100 GPU and a AMD Genoa CPU to enable as many confidential-computing features as possible.
I am running a confidential VM based on Ubuntu 22.04.2. This includes kernel version `6.2.0-37-generic`. 

When installing cuda version `535.86.10` in that VM I can list the H100 by calling `nvidia-smi`. 
When installing cuda version `535.104.05` in the same VM I can not list the GPU, instead I am faced with a `No devices found` error.

In both cases the cc mode of the GPU is disabled using [gpu_cc_tool.py](https://github.com/NVIDIA/nvtrust/blob/main/host_tools/python/gpu_cc_tool.py) on the host.
I can reliably reproduce the error by uninstalling one cuda version using `sudo /usr/bin/nvidia-uninstall` and installing the other version. With or without rebooting.

When comparing straces between the two versions it seems like there is an ioctl to `/dev/nvidia-uvm` which returns some information that nvidia-smi does not like. But my understanding is too limited here.

I expected cuda version `535.104.05` to work based on [this](https://docs.nvidia.com/confidential-compute-early-access-release-notes.pdf) document, version RN-11468-001.

Do you have any information here?

- cuda version 535.86.10 installed. command to generate trace `strace -o 535.86.10 nvidia-smi`: [gist](https://gist.github.com/derpsteb/2f018d4709bb408cde0f2a9419a96a2c)
- cuda version 535.104.05 installed. command to generate trace `strace -o 535.104.05 nvidia-smi`: [gist](https://gist.github.com/derpsteb/093276f052e03c4f686077dda19fbaf7)

**Comment by Tan-YiFan** [comment]
> In both cases the cc mode of the GPU is disabled using [gpu_cc_tool.py](https://github.com/NVIDIA/nvtrust/blob/main/host_tools/python/gpu_cc_tool.py) on the host.

The cc mode should be set to on or devtools.

Besides, could you provide the output of `dmesg` of 535.104.05? `dmesg` information tends to be more useful than strace.

**Comment by derpsteb** [comment]
Even when setting the GPU to devtools mode the behavior persists.

dmesg output from executing `nvidia-smi`: 
```
[  359.369719] nvidia 0000:01:00.0: swiotlb buffer is full (sz: 368640 bytes), total 524288 (slots), used 611 (slots)
[  359.370127] NVRM: GPU 0000:01:00.0: RmInitAdapter failed! (0x62:0x59:2393)
[  359.371773] NVRM: GPU 0000:01:00.0: rm_init_adapter failed, device minor number 0
[  359.449224] nvidia 0000:01:00.0: swiotlb buffer is full (sz: 368640 bytes), total 524288 (slots), used 611 (slots)
[  359.449545] NVRM: GPU 0000:01:00.0: RmInitAdapter failed! (0x62:0x59:2393)
[  359.451110] NVRM: GPU 0000:01:00.0: rm_init_adapter failed, device minor number 0
```
Full output can be found [here](https://gist.github.com/derpsteb/b4d0a45c8ed1ce0303ecf5745b495883).

[This](https://github.com/AMDESE/AMDSEV/issues/177) issue also seems interesting as it hints at why CC mode off + CVM won't work.

**Comment by Tan-YiFan** [comment]
1. Did you install the open kernel module? (adding `-m=kernel-open` in cuda or nvidia installer)
2. Maybe you can refer to https://github.com/NVIDIA/open-gpu-kernel-modules/issues/531#issuecomment-1673110540

**Comment by derpsteb** [comment]
I installed the cuda versions without `-m=kernel-open`. I would expect the proprietary version to be more likely to work. 
Is there documentation stating that only the open kernel model has CC support?

**Comment by Tan-YiFan** [comment]
The procedure in https://docs.nvidia.com/confidential-computing-deployment-guide.pdf uses open kernel module.

I do not know any documentation that says "only" open kernel module support CC. However, I deep dive into the installer:

First, execute the nvidia installer with extract only:
```
wget https://us.download.nvidia.com/XFree86/Linux-x86_64/535.104.05/NVIDIA-Linux-x86_64-535.104.05.run
./NVIDIA-Linux-x86_64-535.104.05.run -x
cd NVIDIA-Linux-x86_64-535.104.05
```

Then, function symbols could be found in the binary of open source kernel but not found in proprietary driver.
```
nm -a ./kernel/nvidia/nv-kernel.o_binary | grep -i confcomput | wc -l                                                                                                                                                                                                                                                                                                                                                                                                                 
0

nm -a ./kernel-open/nvidia/nv-kernel.o_binary | grep -i confcomput | wc -l                                                                                                                                                                                                                                                                                                                                                                                                            
79
```

Therefore, I could assume that the proprietary does not support CC.

**Comment by derpsteb** [comment]
That is interesting. But could also be that the propriertary drive is built without symbols.

In any case: I think my problem was related to not running the persistence daemon. With it running I can successfully list the device with the above version. Irrespective of the CC mode of the GPU. 
Disabling CC mode still produces the error from the AMD issue: https://github.com/AMDESE/AMDSEV/issues/177

Thanks for your help!

**Comment by Tan-YiFan** [comment]
OK.

By the way, may I ask you, does Constellation project of Edgeless Systems support H100 CC now?

**Comment by steven-bellock** [comment]
For confidential compute, at a minimum, `nvidia.ko` relies on the Linux Kernel Crypto API to perform cryptography operations and those symbols can/should not be used by the proprietary driver.

**Comment by derpsteb** [comment]
Oh sorry didn't see your question there @Tan-YiFan. Currently there is still no support on the major CSPs for CVMs + H100s. We are working on something different there ;)
