### ISSUE TITLE
Confidential Compute GPUs Ready state: not-ready even after attestation

### ISSUE THREAD

**Issue by seungsoo-lee** [NVIDIA/nvtrust#37]
My machine's specs:

CPU: Dual AMD EPYC 9224 16-Core Processor
GPU: H100 10de:2331 (vbios: 96.00.5E.00.01 cuda: 12.2 nvidia driver: 535.86.10)
Host OS: Ubuntu 22.04 with 5.19.0-rc6-snp-host-c4daeffce56e kernel
Guest OS: Ubuntu 22.04.2 with 5.19.0-rc6-snp-guest-c4daeffce56e kernel

On the guest VM, run 
```
cclab@guest:~$ source /shared/nvAttest/bin/activate
(nvAttest) cclab@guest:~$ python3 -m verifier.cc_admin --user_mode
```

and the results are as follows;
```
Number of GPUs available : 1
-----------------------------------
Fetching GPU 0 information from GPU driver.
Using the Nonce generated by Local GPU Verifier
VERIFYING GPU : 0
	Driver version fetched : 535.86.10
	VBIOS version fetched : 96.00.5e.00.01
	Validating GPU certificate chains.
		GPU attestation report certificate chain validation successful.
			The certificate chain revocation status verification successful.
	Authenticating attestation report
		The nonce in the SPDM GET MEASUREMENT request message is matching with the generated nonce.
		Driver version fetched from the attestation report : 535.86.10
		VBIOS version fetched from the attestation report : 96.00.5e.00.01
		Attestation report signature verification successful.
		Attestation report verification successful.
	Authenticating the RIMs.
		Authenticating Driver RIM
			Fetching the driver RIM from the RIM service.
			RIM Schema validation passed.
			driver RIM certificate chain verification successful.
			The certificate chain revocation status verification successful.
			driver RIM signature verification successful.
			Driver RIM verification successful
		Authenticating VBIOS RIM.
			Fetching the VBIOS RIM from the RIM service.
			RIM Schema validation passed.
			vbios RIM certificate chain verification successful.
			The certificate chain revocation status verification successful.
			vbios RIM signature verification successful.
			VBIOS RIM verification successful
	Comparing measurements (runtime vs golden)
			The runtime measurements are matching with the golden measurements.
		GPU is in expected state.
	GPU 0 verified successfully.
	GPU Attested Successfully
```

However, the Confidential Compute GPUs Ready state is still not ready.
```
(nvAttest) cclab@guest:~$ nvidia-smi conf-compute -grs
Confidential Compute GPUs Ready state: not-ready
```

Do you have any idea for this?

**Comment by hiroki-chen** [comment]
You need to

```sh
sudo nvidia-smi conf-compute -srs 1
```

to manually enable this. This attestation script will not set this flag.

**Comment by seungsoo-lee** [comment]
@hiroki-chen 

Do you know what's differences between ```Confidential Compute GPUs Ready state``` and ```CC status``` ?

I thought that if the attestation on the guest VM is success, the Confidential Compute GPUs Ready state becomes Ready. 

And I thouhgt that ```CC status``` on the guest VM shows just whether the CC mode on or off from the host.

Am I correctly understanding?

**Comment by Tan-YiFan** [comment]
CC state is configured by the host.Ready state is configured by the guest admin or attestation tool.

**Comment by seungsoo-lee** [comment]
@Tan-YiFan 

then, if ```python3 -m verifier.cc_admin --allow_hold_cert --user_mode``` is successfully executed (True), ```onfidential Compute GPUs Ready state``` should become 'Ready' from 'not-ready' right?

**Comment by Tan-YiFan** [comment]
The verifier calls `set_gpu_ready_state` to change the ready state. You could search this function in the repo and trace it if it is called.

**Comment by seungsoo-lee** [comment]
@Tan-YiFan 

Then, in this case, the verifier did not to change the ready state? So, it seems a bug?

**Comment by Tan-YiFan** [comment]
Possibly. I have little knowledge about attestation and this tool.

**Comment by hiroki-chen** [comment]
> @Tan-YiFan
> 
> Then, in this case, the verifier did not to change the ready state? So, it seems a bug?

You should run the script as `sudo` to change the status.

```python
```

**Comment by thisiskarthikj** [comment]
@seungsoo-lee 
I second @hiroki-chen 's response. 

The GA version will have a better / cleaner documentation of the tool but when you specify "user_mode", you are essentially saying the SDK to skip setting the GPU to ready state but in order for setting the GPU to a ready state (non user mode), you should execute the SDK as sudo user. 

Please re-open this issue if required.
