### ISSUE TITLE
Support for Intel TDX GPU?

### ISSUE THREAD

**Issue by weikengchen** [NVIDIA/nvtrust#4]
Hi Nvidia,

Recalled that from Phil Rogers's presentation in Confidential Computing Summit 2023, it mentioned that the support may come for AMD SEV-SNP and Intel TDX 1.0 CPUs. Combinations of AMD + H100 is still rare among cloud servers, and one may have to customize-build such a machine, but TDX + H100 is available in a few cloud providers such as Coreweave today.

I wonder if support for TDX would be released very soon, following the release of the AMD support?

Thanks,
Weikeng

**Comment by weikengchen** [comment]
And let me explain the timeliness of this issue---if TDX support is expected to arrive soon, then we would refrain spending too much effort in securing AMD Milan + H100, which, if required customized build, could be very challenging.

**Comment by Tan-YiFan** [comment]
Also hope H100 confidential computing support for Intel TDX would be released very soon.

By the way, may I ask @weikengchen: Enabling confidential computing (CC) mode requires the virtual machine a CVM. However, most GPU cloud providers do not provide a choice of CVM. In this situation, how can I enable CC mode?

Thanks!

**Comment by weikengchen** [comment]
Hi @Tan-YiFan, I think it requires customization efforts from the cloud providers. I asked Coreweave, it is possible for large deployment, so needs discussion and negotiations. I am also looking into Microsoft Azure, which has some private previews that may expand to H100 soon. We will see, but I think these two are the short-term solutions.

There is a significant shortage of H100 availability nationwide in the US even IDC appears to be very occupied.

Ideally, it would be super great if Nvidia enables some development mode where a user can experiment with H100 for Confidential Computing although the VM is not being initialized as the development guideline says. In addition, if there is going to be a simulator that enables people to do small tests without having access to H100, it would be even better, but I guess it would be difficult. 

I can see that the modifications to the VM may be unavoidable since some are related to patches to the kernel.

**Comment by weikengchen** [comment]
On the good side, all of these are expected to be short-term problems, and when the supply chain of H100 becomes more healthy, when the kernel support is more stable, situations will improve. 

We should not stop ourselves waiting for the SDK. We should start finding a concrete use case. Unlike SGX which would require a lot of changes to the applications, the current architecture of CC seems to minimize the deployment overhead.

**Comment by Tan-YiFan** [comment]
Hi @weikengchen ,

**Comment by jiazhang0** [comment]
@Tan-YiFan However, we never see any "consumer" code to use the CPU TEE info `cpuCapability`.

**Comment by Tan-YiFan** [comment]
The [Confidential Computing Deployment Guide](https://docs.nvidia.com/confidential-computing-deployment-guide.pdf) was update to version 2.0 on August 30th. TDX support is added.

**Comment by Tan-YiFan** [comment]
> @Tan-YiFan However, we never see any "consumer" code to use the CPU TEE info `cpuCapability` in NV opensource kernel driver. So I'm not quite sure "Enabling confidential computing (CC) mode requires the virtual machine a CVM" is necessary.

Well, the [Confidential Computing Deployment Guide](https://docs.nvidia.com/confidential-computing-deployment-guide.pdf) says on page 6 that:

> CC requires CPUs and GPUs with specific functionality that enable the security outlined by the CC Consortium.
> * CPU Requirements
>   * AMD with SEV-SNP support
>   * Intel with TDX support

I just follow the above, without validating it by reading relative source code. A CVM might not be necessary, but I do not have access to H100. So I cannot have a try.

**Comment by rnertney** [comment]
Closing out as we released the EA2 with TDX support
