### ISSUE TITLE
New CC features in R550 Driver

### ISSUE THREAD

**Issue by Tan-YiFan** [NVIDIA/nvtrust#40]
I saw some update of CC-related code in Nvidia driver [550.40.07](https://github.com/NVIDIA/open-gpu-kernel-modules/tree/550.40.07). Are there any new CC features coming soon?

Some of the updates:

* Key update at `confComputeKeyStoreUpdateKey_GH100` (implemented for key rotation?)
* IV rotate at `uvm_conf_computing_rotate_channel_ivs_below_limit`
* MIG support `multiGpuMode`

**Comment by steven-bellock** [comment]
@Tan-YiFan With https://github.com/NVIDIA/open-gpu-kernel-modules/releases/tag/570.86.15 rotation of symmetric keys has been implemented.
