### ISSUE TITLE
Issues of kernel lockdown from secure boot enabled and direct PCI access of script gpu_cc_tool.py

### ISSUE THREAD

**Issue by tingyuz** [NVIDIA/nvtrust#48]
I have a Dell R760 server (CPU Intel Emerald Rapids) with H-100 GPU attached, running Ubuntu 23.01. The TDx is enabled on the server and was verified by dmesg output, then I followed confidential-computing-deployment-guide.pdf from nvidia website to configure the GPU to cc mode on. When I ran gpu_cc_tool.py, it threw error like below

$sudo python3 gpu_cc_tool.py --gpu-name=H100 --query-cc-mode

NVIDIA GPU Tools version 535.86.06
  File "/shared/nvtrust/host_tools/python/gpu_cc_tool.py", line 127, in find_gpus_sysfs
    dev = Gpu(dev_path=dev_path)
  File "/shared/nvtrust/host_tools/python/gpu_cc_tool.py", line 2063, in __init__
    raise BrokenGpuError()
2023-10-20,20:56:11.177 ERROR    GPU /sys/bus/pci/devices/0000:02:00.0 broken: **Permission Denied**. 
2023-10-20,20:56:11.178 ERROR    Config space working True
Traceback (most recent call last):
  File "/shared/nvtrust/host_tools/python/gpu_cc_tool.py", line 127, in find_gpus_sysfs
    dev = Gpu(dev_path=dev_path)
  File "/shared/nvtrust/host_tools/python/gpu_cc_tool.py", line 2063, in __init__
    raise BrokenGpuError()
__main__.BrokenGpuError

Checked with dmesg and I noticed this: 

[ 2526.471043] Lockdown: python3: direct PCI access is restricted; see man kernel_lockdown.7

So I guess the issue of "permission denied" from the script output was due to the kernel lockdown ( due to secure boot on).  However based on the user guide "turning on secure boot" in the Bios is required to have H-100 GPU working in the cc mode. This seems a contradiction. Can someone shed some lights here?

**Comment by tingyuz** [comment]
we ran the script on the host, not a VM.

**Comment by Tan-YiFan** [comment]
Try modifying `mmio_access_type` to `sysfs`.

**Comment by tingyuz** [comment]
I've tried to set it to "sysfs" but still have the same issue. 

If I disable secure boot on, I was able to run the script with success. However as I mentioned in the original post, it violates what the user guide requirement ( set secure boot on for cc on mode).

**Comment by YurkoWasHere** [comment]
@tingyuz Have you had any luck getting this working? If so what is your setup?

**Comment by rnertney** [comment]
Please try the latest 550 driver (General Access) and the latest nvTrust github. I seem to recall this issue (or something similar), but don't have a strong recollection. 

Please also note that we are only (currently) testing on Ubuntu 22.04. If you are still seeing issues, please reopen a ticket.
