### ISSUE TITLE
plan to support for other cards

### ISSUE THREAD

**Issue by ramrattle** [NVIDIA/nvtrust#50]
Hi, I wanted to know if nvidia has any plans to support confidential computing and attestation for other cards, Im interested in telco focused  cards like AX800 etc.

Will be helpful if someone can share any public information on this.

**Comment by rnertney** [comment]
Ampere cards are not supported, as they do not have the hardware to support NVIDIA Trusted Computing modes like CC.

As the solution is expanded to other supported SKUs, this repository will be updated alongside it.
