### ISSUE TITLE
OVMF PCI Host bridge error on snp-latest

### ISSUE THREAD

**Issue by clauverjat** [NVIDIA/nvtrust#56]
Hello,

I am trying to run an AMD SEV SNP Confidential VM with a Nvidia H100 in CC mode. Specifically, I am trying to make it work with the **snp-latest branch** from the AMDESE/AMDSEV repo (i.e. the branch that uses Linux kernel version 6.9.0-rc7). I am hitting an error when trying to boot the guest with the PCI passthrough. The error occurs before reaching the linux kernel since it happens in the guest firmware initialization (OVMF).

###  Steps to reproduce
```
git clone https://github.com/AMDESE/AMDSEV.git
cd AMDSEV/
git checkout snp-latest
```
Then I patched `common.sh` adding the following lines (in order to add configure the kernel appropriately): 
```
run_cmd ./scripts/config --enable CONFIG_CRYPTO_ECC
run_cmd ./scripts/config --enable CONFIG_CRYPTO_ECDH
run_cmd ./scripts/config --enable CONFIG_CRYPTO_ECDSA
run_cmd ./scripts/config --enable CONFIG_CGROUP_MISC
```

Installing the build depencies : 
```
sudo apt install -y python3-venv ninja-build libglib2.0-dev python-is-python3 nasm iasl flex bison libelf-dev debhelper libslirp-dev

# From Nvidia deployment guide:
sudo apt install -y ninja-build iasl nasm flex bison openssl dkms autoconf \
zlib1g-dev python3-pip libncurses-dev libssl-dev libelf-dev libudev-dev libpci-dev \
libiberty-dev libtool libpango1.0-dev libjpeg8-dev \
libpixman-1-dev libcairo2-dev libgif-dev libglib2.0-dev git-lfs jq
```
Then building
```
./build.sh --package
```

I am **not** applying the two linux patches from the nvtrust repo (I figure they might no longer be needed since I am building a newer kernel)
```
$ patch -p1 -l < ../../iommu_pagefault.patch
$ patch -p1 -l < ../../iommu_pagesize.patch
```

Preparing the host 
```
sudo cp kvm.conf /etc/modprobe.d/
cd snp-release-<date>/
sudo ./install.sh
```
Rebooting and selecting the right kernel
```
ubuntu@host:~$ uname -r
6.9.0-rc7-snp-host-05b10142ac6a
```

Following the "Preparing the Guest" steps (omitted here)

Configuring the GPU 
Obtain some information
```
$ lspci -n -d 10de:
82:00.0 0302: 10de:2331 (rev a1)
```
Setting the GPU in dev CC mode and activating PCI VFIO for the device.
```
sudo python3 ./nvidia_gpu_tools.py --gpu=0 --query-cc-mode
sudo python3 ./nvidia_gpu_tools.py --gpu=0 --set-cc-mode=devtools --reset-after-cc-mode-switch
sudo sh -c "echo 10de 2331 > /sys/bus/pci/drivers/vfio-pci/new_id
```

Launch guest VM
Set the appropriate values in the vars : 
```
export AMD_SEV_DIR=/path/to/AMDSEV/snp-release-<date>
export VDD_IMAGE=path/to/disk.qcow2

#Hardware Settings

export NVIDIA_GPU=82:00.0
export MEM=64 #in GBs
export FWDPORT=9899
```
Launching guest (with sev-snp and GPU passthrough)
```
cp $AMD_SEV_DIR/usr/local/share/qemu/OVMF_VARS.fd $AMD_SEV_DIR/usr/local/share/qemu/myguest.fd
sudo $AMD_SEV_DIR/usr/local/bin/qemu-system-x86_64 \
  -machine confidential-guest-support=sev0,vmport=off \
  -object sev-snp-guest,id=sev0,cbitpos=51,reduced-phys-bits=1 \
  -enable-kvm -nographic -no-reboot \
  -cpu EPYC-v4 -machine q35 -smp 12,maxcpus=31 -m ${MEM}G,slots=2,maxmem=512G \
  -bios $AMD_SEV_DIR/usr/local/share/qemu/OVMF_CODE.fd \
  -drive if=pflash,format=raw,unit=0,file=$AMD_SEV_DIR/usr/local/share/qemu/myguest.fd \
  -drive file=$VDD_IMAGE,if=none,id=disk0,format=qcow2 \
  -device virtio-scsi-pci,id=scsi0,disable-legacy=on,iommu_platform=true \
  -device scsi-hd,drive=disk0 \
  -device virtio-net-pci,disable-legacy=on,iommu_platform=true,netdev=vmnic,romfile= \
  -netdev user,id=vmnic,hostfwd=tcp::$FWDPORT-:22 \
  -device pcie-root-port,id=pci.1,bus=pcie.0 \
  -device vfio-pci,host=$NVIDIA_GPU,bus=pci.1 \
  -fw_cfg name=opt/ovmf/X-PciMmio64Mb,string=262144
```
The boot fails with an OVMF error :
```
[...]
ProtectUefiImage failed to create image properties record
Select Item: 0x0
FW CFG Signature: 0x554D4551
Select Item: 0x1
FW CFG Revision: 0x3
QemuFwCfg interface (DMA) is supported.
Select Item: 0x19
Select Item: 0x19
PciHostBridgeUtilityInitRootBridge: populated root bus 0, with room for 255 subordinate bus(es)
RootBridge: PciRoot(0x0)
  Support/Attr: 70069 / 70069
    DmaAbove4G: No
NoExtConfSpace: No
     AllocAttr: 3 (CombineMemPMem Mem64Decode)
           Bus: 0 - FF Translation=0
            Io: 6000 - FFFF Translation=0
           Mem: 80000000 - DFFFFFFF Translation=0
    MemAbove4G: C000000000 - FFFFFFFFFF Translation=0
          PMem: FFFFFFFFFFFFFFFF - 0 Translation=0
   PMemAbove4G: FFFFFFFFFFFFFFFF - 0 Translation=0
PciHostBridgeDxe: IntersectMemoryDescriptor: desc [FD00000000, 10000000000) type 1 cap 8000000000026000 conflicts with aperture [C000000000, 10000000000) cap 1

ASSERT_EFI_ERROR (Status = Invalid Parameter)
ASSERT [PciHostBridgeDxe] /home/ubuntu/corentin/AMDSEV/ovmf/MdeModulePkg/Bus/Pci/PciHostBridgeDxe/PciHostBridge.c(550): !(((INTN)(RETURN_STATUS)(Status)) < 0)
```

Note that the error disappears if one boots the guest without trying the pass the GPU device. Also there is no error if I keep everything but remove the option "-fw_cfg name=opt/ovmf/X-PciMmio64Mb,string=262144" (but not really useful since I cannot use the device then).

Any idea on how to solve this issue ?

Thanks

**Comment by benschlueter** [comment]
AFAIK it is caused by a too-big MMIO address space. The h100 needs at least 128GiB but 256GiB space cause the issue, so I just adjusted the value to be something in between and it worked 

```
-fw_cfg name=opt/ovmf/X-PciMmio64Mb,string=151072 \
```

**Comment by clauverjat** [comment]
Thanks @benschlueter replacing the fw_cmd with yours solved the OVMF issue. I am not there yet though, with the OVMF out of the way, I can boot my OS. Now I've got errors from the Nvidia driver. 

```
[   14.886113] nvidia: loading out-of-tree module taints kernel.
[   14.886129] nvidia: module verification failed: signature and/or required key missing - tainting kernel
[   14.886244] sev-guest sev-guest: Initialized SEV guest driver (using vmpck_id 0)
[   15.093909] nvidia-nvlink: Nvlink Core is being initialized, major device number 239

[   15.094619] ppdev: user-space parallel port driver
[   15.096579] NVRM: The NVIDIA GPU 0000:01:00.0 (PCI ID: 10de:2331)
               NVRM: installed in this system is not supported by the
               NVRM: NVIDIA 555.42.02 driver release.
               NVRM: Please see 'Appendix A - Supported NVIDIA GPU Products'
               NVRM: in this release's README, available on the operating system
               NVRM: specific graphics driver download page at www.nvidia.com.
[   15.097749] nvidia 0000:01:00.0: probe with driver nvidia failed with error -1
[   15.097799] NVRM: The NVIDIA probe routine failed for 1 device(s).
[   15.097811] NVRM: None of the NVIDIA devices were initialized.
[   15.098306] nvidia-nvlink: Unregistered Nvlink Core, major device number 239
```
And here is the full dmesg output : https://gist.github.com/clauverjat/2e9f46dff7665d07d4bc5f651ca3d59b

Note that I identified a potential cause for the issue. My GPU VBIOS version is 96.00.30.00.01 (obtained with nvidia-smi), but a minimal version of 96.00.5E.00.00 is required according to the Nvidia deployment guide (though the verification normally comes after this step). 

Looking at other issues on this repo, it seems that I might now hit the same problem as in https://github.com/NVIDIA/nvtrust/issues/31

**Comment by Tan-YiFan** [comment]
Please upgrade the VBIOS by contacting the vendor.

**Comment by clauverjat** [comment]
Hi @Tan-YiFan 

This is ongoing already. We are renting a baremetal server, so we had to ask our cloud provider which then contacted their vendor. I hope it'll happen quickly, but, reasonably, I know it might take a while before they apply the VBIOS upgrade. So in the meantime, can you confirm that an old VBIOS can result in that kind of error ? I want to be sure that I go as far as I can without the VBIOS upgrade.

**Comment by rnertney** [comment]
Also, please note that the NVIDIA Trusted Computing Solutions (such as CC) are only currently supported on our Enterprise drivers, this currently encompasses:

550.54.14
550.54.15
550.90.07

I will get this list added to our documentation and ensure it is up to date.

**Comment by clauverjat** [comment]
Hello @rnertney,

Our system got a VBIOS update and we are now running with VBIOS version 96.00.9F.00.01. After the update, I can run the nvtrust guest tools. I ran the `guest_tools/attestation_sdk/tests/SmallCombinedTest.py` script and got an output with "GPU Attested Successfully", which seems promising. 
However, we are unable to use the GPU for compute (GPU in ERR! state).

We've tested with two different CUDA/driver combinations:
* Driver Version: 560.28.03 | CUDA Version: 12.6
* Driver Version: 550.54.14 | CUDA Version: 12.4

This brings me to my first question : Is Confidential Compute (CC) compatible with the latest 560 drivers? Your last message suggests that CC might only work with the 550 drivers, but this seems a bit strange to me.

If the 560 driver is indeed supposed to work, here’s the dmesg output while the system is running driver version 560. It includes NVRM nvAssertFailed errors that are likely related to the issue: [dmesg output](https://gist.github.com/clauverjat/bbf20976fe8cf512428095996e3d0616#file-gistfile1-txt-L727).

**Comment by Tan-YiFan** [comment]
Please check:

1. You have enabled the cc mode in the host.
2. Run `nvidia-persistenced --uvm-persistence-mode` before any GPU related command including `nvidia-smi`
3. The guest kernel has loaded `aesni` related kernel module 

I also suggest trying 535.104.05 module.

**Comment by Tan-YiFan** [comment]
Did you execute `nvidia-smi -srs 1` (set ready state to 1)

**Comment by clauverjat** [comment]
Hi @Tan-YiFan,

> Did you execute nvidia-smi conf-compute -srs 1 (set ready state to 1)

No I didn't, should I ? (I am gonna try next)

In the meantime here are the results of my test with driver 535.104.05 

## Test with driver 535.104.05 
Summary: Nvidia-persistenced failed

### Config of the guest: 

- OS: Ubuntu 22.04 (jammy)
- Kernel: 6.9.0-snp-guest
- Installed driver: 535.104.05 (as suggested)
- Installed CUDA toolkit : 12.2

### Guest configuration (after the proper snp kernel where installed):
```
wget https://us.download.nvidia.com/tesla/535.104.05/nvidia-driver-local-repo-ubuntu2204-535.104.05_1.0-1_amd64.deb
sudo dpkg -i nvidia-driver-local-repo-ubuntu2204-535.104.05_1.0-1_amd64.deb

wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
sudo dpkg -i cuda-keyring_1.1-1_all.deb
sudo apt-get update
sudo apt-get -y install cuda-12-2

# Configuring nvidia-persistenced service
# ...

# Reboot
```

### Result

```
ubuntu@ubuntu:~$ sudo systemctl status nvidia-persistenced
× nvidia-persistenced.service - NVIDIA Persistence Daemon
     Loaded: loaded (/lib/systemd/system/nvidia-persistenced.service; static)
     Active: failed (Result: exit-code) since Wed 2024-08-21 13:50:17 UTC; 5min ago
    Process: 664 ExecStart=/usr/bin/nvidia-persistenced --user nvidia-persistenced --uvm-persistence-mode --verbose (code=exited, status=1/FAILURE)
    Process: 728 ExecStopPost=/bin/rm -rf /var/run/nvidia-persistenced (code=exited, status=0/SUCCESS)
        CPU: 178ms

Aug 21 13:50:17 ubuntu systemd[1]: Starting NVIDIA Persistence Daemon...
Aug 21 13:50:17 ubuntu nvidia-persistenced[666]: Verbose syslog connection opened
Aug 21 13:50:17 ubuntu nvidia-persistenced[666]: Now running with user ID 113 and group ID 121
Aug 21 13:50:17 ubuntu nvidia-persistenced[666]: Started (666)
Aug 21 13:50:17 ubuntu nvidia-persistenced[666]: device 0000:01:00.0 - registered
Aug 21 13:50:17 ubuntu nvidia-persistenced[666]: device 0000:01:00.0 - failed to open.
Aug 21 13:50:17 ubuntu nvidia-persistenced[664]: nvidia-persistenced failed to initialize. Check syslog for more details.
Aug 21 13:50:17 ubuntu systemd[1]: nvidia-persistenced.service: Control process exited, code=exited, status=1/FAILURE
Aug 21 13:50:17 ubuntu systemd[1]: nvidia-persistenced.service: Failed with result 'exit-code'.
Aug 21 13:50:17 ubuntu systemd[1]: Failed to start NVIDIA Persistence Daemon.

ubuntu@ubuntu:~$ nvidia-smi 
No devices were found

ubuntu@ubuntu:~$ sudo dmesg
# beginning of the dmesg output is omitted to save space
[   18.024330] nvidia-nvlink: Nvlink Core is being initialized, major device number 239
[   18.024344] NVRM: loading NVIDIA UNIX x86_64 Kernel Module  560.28.03  Thu Jul 18 19:32:18 UTC 2024
[   18.158345] nvidia-modeset: Loading NVIDIA Kernel Mode Setting Driver for UNIX platforms  560.28.03  Thu Jul 18 20:27:27 UTC 2024
[   18.191985] audit: type=1400 audit(1724248216.707:8): apparmor="STATUS" operation="profile_load" profile="unconfined" name="ubuntu_pro_apt_news" pid=593 comm="apparmor_parser"
[   18.205549] audit: type=1400 audit(1724248216.719:9): apparmor="STATUS" operation="profile_load" profile="unconfined" name="/usr/lib/snapd/snap-confine" pid=597 comm="apparmor_parser"
[   18.205589] audit: type=1400 audit(1724248216.719:10): apparmor="STATUS" operation="profile_load" profile="unconfined" name="/usr/lib/snapd/snap-confine//mount-namespace-capture-helper" pid=597 comm="apparmor_parser"
[   18.213258] [drm] [nvidia-drm] [GPU ID 0x00000100] Loading driver
[   18.226107] audit: type=1400 audit(1724248216.743:11): apparmor="STATUS" operation="profile_load" profile="unconfined" name="tcpdump" pid=596 comm="apparmor_parser"
[   18.295478] NVRM: GPU 0000:01:00.0: RmInitAdapter failed! (0x22:0x38:880)
[   18.297093] NVRM: GPU 0000:01:00.0: rm_init_adapter failed, device minor number 0
[   18.318091] [drm:nv_drm_load [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000100] Failed to allocate NvKmsKapiDevice
[   18.320482] [drm:nv_drm_register_drm_device [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000100] Failed to register device
[   18.340114] nvidia_uvm: module uses symbols nvUvmInterfaceDisableAccessCntr from proprietary module nvidia, inheriting taint.
[   18.371352] nvidia-uvm: Loaded the UVM driver, major device number 237.
[   18.740885] NVRM: GPU 0000:01:00.0: RmInitAdapter failed! (0x22:0x38:880)
[   18.743372] NVRM: GPU 0000:01:00.0: rm_init_adapter failed, device minor number 0
[   18.819872] NVRM: GPU 0000:01:00.0: RmInitAdapter failed! (0x22:0x38:880)
[   18.821706] NVRM: GPU 0000:01:00.0: rm_init_adapter failed, device minor number 0
[   19.292517] loop3: detected capacity change from 0 to 8
[   50.323402] NVRM: GPU 0000:01:00.0: RmInitAdapter failed! (0x22:0x38:880)
[   50.325597] NVRM: GPU 0000:01:00.0: rm_init_adapter failed, device minor number 0
[   83.061967] NVRM: GPU 0000:01:00.0: RmInitAdapter failed! (0x22:0x38:880)
[   83.066463] NVRM: GPU 0000:01:00.0: rm_init_adapter failed, device minor number 0
[   85.968745] NVRM: GPU 0000:01:00.0: RmInitAdapter failed! (0x22:0x38:880)
[   85.973705] NVRM: GPU 0000:01:00.0: rm_init_adapter failed, device minor number 0
[   86.102415] NVRM: GPU 0000:01:00.0: RmInitAdapter failed! (0x22:0x38:880)
[   86.107021] NVRM: GPU 0000:01:00.0: rm_init_adapter failed, device minor number 0
[   86.171687] NVRM: GPU 0000:01:00.0: RmInitAdapter failed! (0x22:0x38:880)
[   86.173727] NVRM: GPU 0000:01:00.0: rm_init_adapter failed, device minor number 0
[   86.271069] NVRM: GPU 0000:01:00.0: RmInitAdapter failed! (0x22:0x38:880)
[   86.274944] NVRM: GPU 0000:01:00.0: rm_init_adapter failed, device minor number 0
[   86.381771] NVRM: GPU 0000:01:00.0: RmInitAdapter failed! (0x22:0x38:880)
[   86.386366] NVRM: GPU 0000:01:00.0: rm_init_adapter failed, device minor number 0
[   86.475908] NVRM: GPU 0000:01:00.0: RmInitAdapter failed! (0x22:0x38:880)
[   86.480248] NVRM: GPU 0000:01:00.0: rm_init_adapter failed, device minor number 0
[  379.333352] NVRM: GPU 0000:01:00.0: RmInitAdapter failed! (0x22:0x38:880)
[  379.338595] NVRM: GPU 0000:01:00.0: rm_init_adapter failed, device minor number 0
[  382.846493] NVRM: GPU 0000:01:00.0: RmInitAdapter failed! (0x22:0x38:880)
[  382.850442] NVRM: GPU 0000:01:00.0: rm_init_adapter failed, device minor number 0
```

## Additional information

[535.104.05-nvidia-bug-report.log.gz](https://github.com/user-attachments/files/16692766/535.104.05-nvidia-bug-report.log.gz)

**Comment by Tan-YiFan** [comment]
You should execute `nvidia-smi conf-compute -srs 1` before you run python code.

The log shows driver version is 560.28.03. Please uninstall existing driver before install a new one. After reboot, you would see the latest-installed version.

Cuda 12.3 (driver 54x.xx) and 12.5 (driver 56x.xx) are merging new features of nvidia cc and thus not recommended for install. Cuda 12.2.2 (driver 535.104.05) and 12.4 (driver 550.xx) are stable regarding cc feature, while 12.4 has better performance in cc.

**Comment by clauverjat** [comment]
> You should execute nvidia-smi conf-compute -srs 1 before you run python code.


Oh, that did the trick! Setting the Confidential Compute GPU to Ready State was exactly what I needed to do.

I retried on Ubuntu Jammy with the NVIDIA driver version 550.90.07 and CUDA 12.6, and after running the `nvidia-smi conf-compute -srs 1` command, my script executed successfully.

Surprisingly, I had run almost identical instructions on a system with VBIOS 96.00.74.00.1C (so without your command), and I could execute the script. This makes me wonder if I might have inadvertently triggered the Ready State in some other way, or if perhaps older VBIOS versions don’t require this step to enable the GPU?

In any case, it’s great to see everything working with driver 550.90.07.

That said, I’m still seeing the following kernel errors in dmesg:
```
[   19.441219] ACPI Warning: \_SB.PCI0.S20.S00._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20230628/nsarguments-61)
[   19.703498] loop3: detected capacity change from 0 to 8
[   22.302161] NVRM: nvAssertFailed: Assertion failed: 0 @ g_kern_gmmu_nvoc.h:1967
[   22.302173] NVRM: nvAssertFailed: Assertion failed: 0 @ g_kern_gmmu_nvoc.h:1967
``` 
I don't know what to make of them... Is it expected ? Should I try to get rid of these?

Thanks for your help!

**Comment by clauverjat** [comment]
> The log shows driver version is 560.28.03. Please uninstall existing driver before install a new one. After reboot, you would see the latest-installed version.

Hmm, I shared the logs from different attempts with different VM and configuration, which log are you talking about? If you are talking about  the dmesg output from this message :
> If the 560 driver is indeed supposed to work, here’s the dmesg output while the system is running driver version 560. It includes NVRM nvAssertFailed errors that are likely related to the issue: [dmesg output](https://gist.github.com/clauverjat/bbf20976fe8cf512428095996e3d0616#file-gistfile1-txt-L727).

Then this is normal driver version 560 is expected. But in all cases the driver announced should match the logs.

>  Please uninstall existing driver before install a new one. After reboot, you would see the latest-installed version.

The new attempt I did today was on fresh VM to make sure of the version in use.

Anyway, thanks for providing information about the recommended drivers for using CC mode. I will stick to driver 550.xx then.

**Comment by Tan-YiFan** [comment]
> [   19.441219] ACPI Warning: \_SB.PCI0.S20.S00._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20230628/nsarguments-61)
[   19.703498] loop3: detected capacity change from 0 to 8
[   22.302161] NVRM: nvAssertFailed: Assertion failed: 0 @ g_kern_gmmu_nvoc.h:1967
[   22.302173] NVRM: nvAssertFailed: Assertion failed: 0 @ g_kern_gmmu_nvoc.h:1967

These lines are expected.

Setting cc mode to devtools (instead of on) would automatically set ready state to on. Executing the attestation script would also set cc mode to on (you can search "ready" in `guest_tools/` of this repo).

The log of 535.104.05 seems to have 560.28.03 installed. But that doesn't matter.

You can close the issue if everything goes well.

**Comment by clauverjat** [comment]
> These lines are expected.

That's reassuring.

> Setting cc mode to devtools (instead of on) would automatically set ready state to on. Executing the attestation script would also set cc mode to on (you can search "ready" in guest_tools/ of this repo).

Makes sense. That could explain my previous experience.

> The log of 535.104.05 seems to have 560.28.03 installed. But that doesn't matter.

Indeed you're right. I missed that. Though since it works now it doesn't matter.

Thanks for your help @Tan-YiFan
