### ISSUE TITLE
"No devices were found" NVIDIA cc with Intel TDX

### ISSUE THREAD

**Issue by VicoinDub** [NVIDIA/nvtrust#64]
I build the host with the newer https://github.com/canonical/tdx repo
* Enabled IOMMU in kernel
> \# edit /etc/default/grub and add
GRUB_CMDLINE_LINUX="intel_iommu=on iommu=pt "

* Enabled VFIO mode
> modprobe vfio vfio_pci
sudo sh -c "echo 10de 2331 > /sys/bus/pci/drivers/vfio-pci/new_id"

* Passed the NVIDIA H100 into the VM
> \# edit .xml.template
<qemu:commandline>
    <qemu:arg value='-machine'/>
    <qemu:arg value='q35'/>
    <qemu:arg value='-machine'/>
    <qemu:arg value='hpet=off'/>
    <qemu:arg value='-nodefaults'/>
    <qemu:arg value='-device'/>
    <qemu:arg value='vfio-pci,host=98:00.0,multifunction=on,addr=0x16'/>
    <qemu:arg value='-fw_cfg'/>
    <qemu:arg value='name=opt/ovmf/X-PciMmio64,string=262144'/>
    <qemu:arg value='-device'/>
    <qemu:arg value='virtio-net-pci,netdev=nic0,bus=pcie.0,addr=0x5'/>
    <qemu:arg value='-netdev'/>
    <qemu:arg value='user,id=nic0,hostfwd=tcp::0-:22'/>
  </qemu:commandline>

Host

`uname -r`
> 6.8.1-e3

`sudo python3 ./nvidia_gpu_tools.py --gpu-bdf=1b:00.0 --set-cc-mode=devtools`
`sudo python3 ./nvidia_gpu_tools.py --gpu-bdf=98:00.0 --query-cc-settings`
> NVIDIA GPU Tools version v2024.02.14o
Command line arguments: ['./nvidia_gpu_tools.py', '--gpu-bdf=98:00.0', '--query-cc-settings']
Topo:
  Intel root port 0000:97:01.0
   GPU 0000:98:00.0 H100-PCIE 0x2331 BAR0 0x226042000000
2024-08-01,20:15:40.556 INFO     Selected GPU 0000:98:00.0 H100-PCIE 0x2331 BAR0 0x226042000000
2024-08-01,20:15:40.556 WARNING  GPU 0000:98:00.0 H100-PCIE 0x2331 BAR0 0x226042000000 has CC mode devtools, some functionality may not work
2024-08-01,20:15:40.618 INFO     GPU 0000:98:00.0 H100-PCIE 0x2331 BAR0 0x226042000000 CC settings:
2024-08-01,20:15:40.618 INFO       enable = 1
2024-08-01,20:15:40.618 INFO       enable-devtools = 1
2024-08-01,20:15:40.618 INFO       enable-bar0-filter = 0
2024-08-01,20:15:40.618 INFO       enable-allow-inband-control = 1
2024-08-01,20:15:40.618 INFO       enable-devtools-allow-inband-control = 1
2024-08-01,20:15:40.618 INFO       enable-bar0-filter-allow-inband-control = 1

Guest
nvidia-driver
> 550.90.07

`ps -aux | grep nvidia-persistenced`

>root 12560 0.2 0.0 2912 2176 ? Ss 11:23 0:00 /usr/bin/nvidia-persistenced --user nvidia-persistenced --uvm-persistence-mode --verbose
nvidia-+ 12562 100 0.0 5376 2176 ? Rs 11:23 0:03 /usr/bin/nvidia-persistenced --user nvidia-persistenced --uvm-persistence-mode --verbose
root 12575 0.0 0.0 7044 2560 pts/0 S+ 11:23 0:00 grep --color=auto nvidia-persistenced

`sudo lspci -nnk  | grep -i nvidia`

>00:16.0 3D controller [0302]: NVIDIA Corporation GH100 [H100 PCIe] [10de:2331] (rev a1)
Subsystem: NVIDIA Corporation GH100 [H100 PCIe] [10de:1626]
Kernel driver in use: nvidia
Kernel modules: nvidiafb, nouveau, nvidia_drm, nvidia

`uname -r`

>6.8.0-35-generic

 Finally,When i run `nvidia-smi`,i got  
> No devices were found
And i see the following in `dmesg`

>[ 1204.121696] nvidia-persiste[11119]: segfault at 44 ip 00007e96bba08c21 sp 00007ffdbcd8f790 error 6 in libnvidia-cfg.so.550.90.07[7e96bba00000+4d000] likely on CPU 15 (core 15, socket 0)
[ 1204.121708] Code: 00 31 c0 48 81 c4 10 08 00 00 5b 5d 41 5c 41 5d 41 5e c3 66 0f 1f 44 00 00 41 55 41 54 48 8d 57 48 55 53 48 89 fb 48 83 ec 28 47 44 00 00 00 00 8b 77 08 8b 3f e8 8e fe ff ff 85 c0 89 c5 75
[ 1204.123427] [drm] [nvidia-drm] [GPU ID 0x00000016] Loading driver
[ 1204.123433] [drm] Initialized nvidia-drm 0.0.0 20160202 for 0000:00:16.0 on minor 0
[ 1209.300006] NVRM: kfspPollForResponse_IMPL: FSP command timed out
[ 1209.300014] NVRM: kfspSendBootCommands_GH100: Sent following content to FSP:
[ 1209.300016] NVRM: kfspSendBootCommands_GH100: version=0x1, size=0x35c, gspFmcSysmemOffset=0x19b780000
[ 1209.300017] NVRM: kfspSendBootCommands_GH100: frtsSysmemOffset=0x0, frtsSysmemSize=0x0
[ 1209.300018] NVRM: kfspSendBootCommands_GH100: frtsVidmemOffset=0x200000, frtsVidmemSize=0x100000
[ 1209.300019] NVRM: kfspSendBootCommands_GH100: gspBootArgsSysmemOffset=0x151229000
[ 1209.300020] NVRM: kfspSendBootCommands_GH100: FSP boot cmds failed. RM cannot boot.
[ 1209.300022] NVRM: kfspDumpDebugState_GH100: GPU 0000:00:16
[ 1209.300023] NVRM: kfspDumpDebugState_GH100: NV_PFSP_FALCON_COMMON_SCRATCH_GROUP_2(0) = 0x9f
[ 1209.300025] NVRM: kfspDumpDebugState_GH100: NV_PFSP_FALCON_COMMON_SCRATCH_GROUP_2(1) = 0x10fd12
[ 1209.300026] NVRM: kfspDumpDebugState_GH100: NV_PFSP_FALCON_COMMON_SCRATCH_GROUP_2(2) = 0x1103c0
[ 1209.300028] NVRM: kfspDumpDebugState_GH100: NV_PFSP_FALCON_COMMON_SCRATCH_GROUP_2(3) = 0x5
[ 1209.300859] NVRM: nvCheckOkFailedNoLog: Check failed: Call timed out [NV_ERR_TIMEOUT] (0x00000065) returned from kfspSendBootCommands_HAL(pGpu, pKernelFsp) @ kernel_gsp_gh100.c:756
[ 1209.301213] NVRM: RmInitAdapter: Cannot initialize GSP firmware RM
[ 1209.945763] NVRM: GPU 0000:00:16.0: RmInitAdapter failed! (0x62:0x65:1784)
[ 1209.947410] nvidia-uvm: Loaded the UVM driver, major device number 236.
[ 1209.948222] NVRM: GPU 0000:00:16.0: rm_init_adapter failed, device minor number 0
[ 1209.955901] [drm] [nvidia-drm] [GPU ID 0x00000016] Unloading driver
[ 1209.971758] nvidia-modeset: Unloading

**Comment by VicoinDub** [comment]
`nvidia-smi -q | grep VBIOS`
No result found.
And the following in `dmesg`
> [73728.997618] NVRM: GPU 0000:00:16.0: rm_init_adapter failed, device minor number 0
[73750.262567] NVRM: kfspPollForResponse_IMPL: FSP command timed out
[73750.262572] NVRM: kfspSendBootCommands_GH100: Sent following content to FSP: 
[73750.262574] NVRM: kfspSendBootCommands_GH100: version=0x1, size=0x35c, gspFmcSysmemOffset=0x13ff00000
[73750.262575] NVRM: kfspSendBootCommands_GH100: frtsSysmemOffset=0x0, frtsSysmemSize=0x0
[73750.262576] NVRM: kfspSendBootCommands_GH100: frtsVidmemOffset=0x200000, frtsVidmemSize=0x100000
[73750.262577] NVRM: kfspSendBootCommands_GH100: gspBootArgsSysmemOffset=0x10dc5a000
[73750.262579] NVRM: kfspSendBootCommands_GH100: FSP boot cmds failed. RM cannot boot.
[73750.262582] NVRM: kfspDumpDebugState_GH100: GPU 0000:00:16
[73750.262583] NVRM: kfspDumpDebugState_GH100: NV_PFSP_FALCON_COMMON_SCRATCH_GROUP_2(0) = 0x9f
[73750.262585] NVRM: kfspDumpDebugState_GH100: NV_PFSP_FALCON_COMMON_SCRATCH_GROUP_2(1) = 0x10fd12
[73750.262587] NVRM: kfspDumpDebugState_GH100: NV_PFSP_FALCON_COMMON_SCRATCH_GROUP_2(2) = 0x1103c0
[73750.262588] NVRM: kfspDumpDebugState_GH100: NV_PFSP_FALCON_COMMON_SCRATCH_GROUP_2(3) = 0x5
[73750.263471] NVRM: nvCheckOkFailedNoLog: Check failed: Call timed out [NV_ERR_TIMEOUT] (0x00000065) returned from kfspSendBootCommands_HAL(pGpu, pKernelFsp) @ kernel_gsp_gh100.c:756
[73750.263830] NVRM: RmInitAdapter: Cannot initialize GSP firmware RM
[73750.929907] NVRM: GPU 0000:00:16.0: RmInitAdapter failed! (0x62:0x65:1784)
[73750.933638] NVRM: GPU 0000:00:16.0: rm_init_adapter failed, device minor number 0

**Comment by VicoinDub** [comment]
I set the GPU into cc-off mode from the host with `nvidia_gpu_tools.py`
`sudo python3 ./nvidia_gpu_tools.py --gpu-bdf=98:00.0 --set-cc-mode=off
--reset-after-cc-mode-switch`

TDX VM Guest
`nvidia-smi` 
>  No devices were found

`dmesg`
> [  194.728078] NVRM: loading NVIDIA UNIX Open Kernel Module for x86_64  550.90.07  Release Build  (dvs-builder@U16-I2-C05-15-3)  Fri May 31 09:44:37 UTC 2024
[  194.819497] nvidia-modeset: Loading NVIDIA UNIX Open Kernel Mode Setting Driver for x86_64  550.90.07  Release Build  (dvs-builder@U16-I2-C05-15-3)  Fri May 31 09:34:25 UTC 2024
[  194.840839] [drm] [nvidia-drm] [GPU ID 0x00000016] Loading driver
[  194.840850] [drm] Initialized nvidia-drm 0.0.0 20160202 for 0000:00:16.0 on minor 0
[  194.958976] nvidia-uvm: Loaded the UVM driver, major device number 236.
[  194.984356] [drm] [nvidia-drm] [GPU ID 0x00000016] Unloading driver
[  194.999983] nvidia-modeset: Unloading
[  195.095255] NVRM: confComputeConstructEngine_IMPL: GPU confidential compute capability is not enabled.
[  195.095264] NVRM: nvAssertFailedNoLog: Assertion failed: 0 @ conf_compute.c:117
[  195.095290] NVRM: osInitNvMapping: *** Cannot attach gpu
[  195.095292] NVRM: RmInitAdapter: osInitNvMapping failed, bailing out of RmInitAdapter
[  195.095307] NVRM: GPU 0000:00:16.0: RmInitAdapter failed! (0x22:0x3f:745)
[  195.098028] nvidia-uvm: Unloaded the UVM driver.
[  195.099497] NVRM: GPU 0000:00:16.0: rm_init_adapter failed, device minor number 0

**Comment by Tan-YiFan** [comment]
Please run `nvidia-smi -q | grep VBIOS` in host or in non-TDX VM

**Comment by VicoinDub** [comment]
I created a non-TDX VM with Ubuntu 22.04, using driver version 535.183.01 and CUDA 12.2. When executing the command 
`nvidia-smi -q | grep VBIOS`, I got the following result:

>     VBIOS Version                         : 96.00.30.00.01
Do I need to update the version to 96.00.5E.00.00? And how do i do it? Thanks!

**Comment by Tan-YiFan** [comment]
The VBIOS should be updated. Please contact the vendor (e.g., Dell, SuperMicro) to update VBIOS

**Comment by Tan-YiFan** [comment]
Maybe you have to update the VBIOS. You can refer to other issues in this repo and questions in https://forums.developer.nvidia.com/c/accelerated-computing/confidential-computing/663

**Comment by VicoinDub** [comment]
@Tan-YiFan I was wondering why it's necessary to contact the vendor (such as Dell or SuperMicro) to update the BIOS of an NVIDIA GPU, rather than reaching out directly to NVIDIA. Could you please clarify?

**Comment by Tan-YiFan** [comment]
You can refer to other issues, or https://forums.developer.nvidia.com/c/accelerated-computing/confidential-computing/663

**Comment by VicoinDub** [comment]
I gave it a shot with both HPE and DELL tools to update the VBIOS on my H100 GPU, but it seems like both times I hit a snag—couldn’t get the BIOS info from the GPU.

Any clue what’s up with that?

tools:

https://support.hpe.com/connect/s/softwaredetails?language=en_US&softwareId=MTX_8185a55ddd114fc59016b4563d&tab=Installation+Instructions

[https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=dthfh 1](https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=dthfh)

errors:

![Image](https://github.com/user-attachments/assets/ba973aa1-f614-4203-a3fa-f2bd5e197e09)



# cat gpu.log 
Current Information for Nvidia Devices:
Number of Nvidia GPUs present on System : 1

Device Information:
98:00.0 3D controller: NVIDIA Corporation GH100 [H100 PCIe] (rev a1)
 
NVIDIA Firmware Information for all Devices:
 

# cat console.log 

HPE Firmware- Video BIOS ( NVIDIA) flashing Utility Version 1.0 - output files saved in *.log
Gathering System information(Check system.log).......................Complete!
NVIDIA Firmware Information for all Devices:
 
Gathering Nvidia Device information(Check gpu.log).......................Complete!
 
Firmware not found in component for  for index 0
 
Utility is not built for this device. This is for Graphics Device with Board ID 0x03B1 series of cards.
Thank you!

**Comment by VicoinDub** [comment]
I have a question: Why would the H100 GPU have a VBIOS version that doesn't support confidential computing features? Were the confidential computing features added later to the H100?

**Comment by Tan-YiFan** [comment]
Please contact the vendor of the server for VBIOS update. I do not suggest updating VBIOS by yourself.

> Why would the H100 GPU have a VBIOS version that doesn't support confidential computing features?

H100 was released in 2022, while CC was accessible several months later (from cuda 12.2.1), about the time this nvtrust repo was released. So early VBIOS version may not support CC.

**Comment by VicoinDub** [comment]
Why does an expired VBIOS lead to the "No device not found" error? 
I'm trying to understand the connection between the BIOS and the "No device not found" error, Can anyone explain this for me? as well as the detailed reasons for this error occurring (there's dmesg information available above). Is it possible that it's not a VBIOS issue?
Besides reaching out to the supplier, how can we fix this problem by ourselves? 
Thank you very much!

**Comment by VicoinDub** [comment]
> Please contact the vendor of the server for VBIOS update. I do not suggest updating VBIOS by yourself.
> 
> > Why would the H100 GPU have a VBIOS version that doesn't support confidential computing features?
> 
> H100 was released in 2022, while CC was accessible several months later (from cuda 12.2.1), about the time this nvtrust repo was released. So early VBIOS version may not support CC.

@Tan-YiFan  Thanks a lot ! You've cleared up a big confusion for me.

**Comment by Tan-YiFan** [comment]
Hello, do you have any unresolved problems? Could you close this issue?
