### ISSUE TITLE
Nsys is not available in CC mode?

### ISSUE THREAD

**Issue by esp-vt** [NVIDIA/nvtrust#74]
Hello, I'm Eunseong.

I currently run a CUDA code in CC mode, and found that nsys didn't return any information apart from OS kernel information.

![Image](https://github.com/user-attachments/assets/b473bdae-fbd5-425c-91af-33bb5bb3d1c7)

Is it not available to use profiling tools like nsys in CC mode? Or did I set something wrong?

Thank you.

**Comment by steven-bellock** [comment]
The GPU needs to be in `devtools` mode. See [here](https://github.com/nvidia/gpu-admin-tools/tree/2311c1700971b0e9e104207b8abc02d097a6527e?tab=readme-ov-file#nvidia-gpu-admin-tools) and 
>devtools - All supported GPU security features are enabled, however blocks preventing DevTools profiling/debugging are lifted

**Comment by esp-vt** [comment]
Thank you very much! And I attach a paper about it.

https://dl.acm.org/doi/pdf/10.1145/3626827
